export const useCountries = () => {
  const countries = ref([
    { code: 'US', name: 'United States', currency: 'USD', flag: '🇺🇸' },
    { code: 'UK', name: 'United Kingdom', currency: 'GBP', flag: '🇬🇧' },
    { code: 'CA', name: 'Canada', currency: 'CAD', flag: '🇨🇦' },
    { code: 'AU', name: 'Australia', currency: 'AUD', flag: '🇦🇺' },
    { code: 'MX', name: 'Mexico', currency: 'MXN', flag: '🇲🇽' },
    { code: 'IN', name: 'India', currency: 'INR', flag: '🇮🇳' },
    { code: 'PH', name: 'Philippines', currency: 'PHP', flag: '🇵🇭' },
    { code: 'NG', name: 'Nigeria', currency: 'NGN', flag: '🇳🇬' },
    { code: 'BR', name: 'Brazil', currency: 'BRL', flag: '🇧🇷' },
    { code: 'CN', name: 'China', currency: 'CNY', flag: '🇨🇳' },
    { code: 'JP', name: 'Japan', currency: 'JPY', flag: '🇯🇵' },
    { code: 'KR', name: 'South Korea', currency: 'KRW', flag: '🇰🇷' },
    { code: 'SG', name: 'Singapore', currency: 'SGD', flag: '🇸🇬' },
    { code: 'HK', name: 'Hong Kong', currency: 'HKD', flag: '🇭🇰' },
    { code: 'TH', name: 'Thailand', currency: 'THB', flag: '🇹🇭' },
    { code: 'MY', name: 'Malaysia', currency: 'MYR', flag: '🇲🇾' },
    { code: 'ID', name: 'Indonesia', currency: 'IDR', flag: '🇮🇩' },
    { code: 'VN', name: 'Vietnam', currency: 'VND', flag: '🇻🇳' },
    { code: 'BD', name: 'Bangladesh', currency: 'BDT', flag: '🇧🇩' },
    { code: 'PK', name: 'Pakistan', currency: 'PKR', flag: '🇵🇰' },
    { code: 'LK', name: 'Sri Lanka', currency: 'LKR', flag: '🇱🇰' },
    { code: 'NP', name: 'Nepal', currency: 'NPR', flag: '🇳🇵' },
    { code: 'MM', name: 'Myanmar', currency: 'MMK', flag: '🇲🇲' },
    { code: 'KH', name: 'Cambodia', currency: 'KHR', flag: '🇰🇭' },
    { code: 'LA', name: 'Laos', currency: 'LAK', flag: '🇱🇦' },
    { code: 'MN', name: 'Mongolia', currency: 'MNT', flag: '🇲🇳' },
    { code: 'RU', name: 'Russia', currency: 'RUB', flag: '🇷🇺' },
    { code: 'UA', name: 'Ukraine', currency: 'UAH', flag: '🇺🇦' },
    { code: 'PL', name: 'Poland', currency: 'PLN', flag: '🇵🇱' },
    { code: 'RO', name: 'Romania', currency: 'RON', flag: '🇷🇴' },
    { code: 'HU', name: 'Hungary', currency: 'HUF', flag: '🇭🇺' },
    { code: 'CZ', name: 'Czech Republic', currency: 'CZK', flag: '🇨🇿' },
    { code: 'SK', name: 'Slovakia', currency: 'EUR', flag: '🇸🇰' },
    { code: 'AT', name: 'Austria', currency: 'EUR', flag: '🇦🇹' },
    { code: 'CH', name: 'Switzerland', currency: 'CHF', flag: '🇨🇭' },
    { code: 'NO', name: 'Norway', currency: 'NOK', flag: '🇳🇴' },
    { code: 'SE', name: 'Sweden', currency: 'SEK', flag: '🇸🇪' },
    { code: 'DK', name: 'Denmark', currency: 'DKK', flag: '🇩🇰' },
    { code: 'FI', name: 'Finland', currency: 'EUR', flag: '🇫🇮' },
    { code: 'NL', name: 'Netherlands', currency: 'EUR', flag: '🇳🇱' },
    { code: 'BE', name: 'Belgium', currency: 'EUR', flag: '🇧🇪' },
    { code: 'FR', name: 'France', currency: 'EUR', flag: '🇫🇷' },
    { code: 'DE', name: 'Germany', currency: 'EUR', flag: '🇩🇪' },
    { code: 'IT', name: 'Italy', currency: 'EUR', flag: '🇮🇹' },
    { code: 'ES', name: 'Spain', currency: 'EUR', flag: '🇪🇸' },
    { code: 'PT', name: 'Portugal', currency: 'EUR', flag: '🇵🇹' },
    { code: 'IE', name: 'Ireland', currency: 'EUR', flag: '🇮🇪' },
    { code: 'GR', name: 'Greece', currency: 'EUR', flag: '🇬🇷' },
    { code: 'TR', name: 'Turkey', currency: 'TRY', flag: '🇹🇷' },
    { code: 'EG', name: 'Egypt', currency: 'EGP', flag: '🇪🇬' },
    { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', flag: '🇸🇦' },
    { code: 'AE', name: 'UAE', currency: 'AED', flag: '🇦🇪' },
    { code: 'QA', name: 'Qatar', currency: 'QAR', flag: '🇶🇦' },
    { code: 'KW', name: 'Kuwait', currency: 'KWD', flag: '🇰🇼' },
    { code: 'BH', name: 'Bahrain', currency: 'BHD', flag: '🇧🇭' },
    { code: 'OM', name: 'Oman', currency: 'OMR', flag: '🇴🇲' },
    { code: 'JO', name: 'Jordan', currency: 'JOD', flag: '🇯🇴' },
    { code: 'LB', name: 'Lebanon', currency: 'LBP', flag: '🇱🇧' },
    { code: 'IL', name: 'Israel', currency: 'ILS', flag: '🇮🇱' },
    { code: 'IR', name: 'Iran', currency: 'IRR', flag: '🇮🇷' },
    { code: 'IQ', name: 'Iraq', currency: 'IQD', flag: '🇮🇶' },
    { code: 'SY', name: 'Syria', currency: 'SYP', flag: '🇸🇾' },
    { code: 'YE', name: 'Yemen', currency: 'YER', flag: '🇾🇪' },
    { code: 'LY', name: 'Libya', currency: 'LYD', flag: '🇱🇾' },
    { code: 'TN', name: 'Tunisia', currency: 'TND', flag: '🇹🇳' },
    { code: 'DZ', name: 'Algeria', currency: 'DZD', flag: '🇩🇿' },
    { code: 'MA', name: 'Morocco', currency: 'MAD', flag: '🇲🇦' },
    { code: 'SN', name: 'Senegal', currency: 'XOF', flag: '🇸🇳' },
    { code: 'ML', name: 'Mali', currency: 'XOF', flag: '🇲🇱' },
    { code: 'NE', name: 'Niger', currency: 'XOF', flag: '🇳🇪' },
    { code: 'BF', name: 'Burkina Faso', currency: 'XOF', flag: '🇧🇫' },
    { code: 'CI', name: 'Ivory Coast', currency: 'XOF', flag: '🇨🇮' },
    { code: 'GH', name: 'Ghana', currency: 'GHS', flag: '🇬🇭' },
    { code: 'CM', name: 'Cameroon', currency: 'XAF', flag: '🇨🇲' },
    { code: 'CG', name: 'Congo', currency: 'XAF', flag: '🇨🇬' },
    { code: 'CD', name: 'DR Congo', currency: 'CDF', flag: '🇨🇩' },
    { code: 'GA', name: 'Gabon', currency: 'XAF', flag: '🇬🇦' },
    { code: 'TD', name: 'Chad', currency: 'XAF', flag: '🇹🇩' },
    { code: 'CF', name: 'Central African Republic', currency: 'XAF', flag: '🇨🇫' },
    { code: 'SS', name: 'South Sudan', currency: 'SSP', flag: '🇸🇸' },
    { code: 'SD', name: 'Sudan', currency: 'SDG', flag: '🇸🇩' },
    { code: 'ET', name: 'Ethiopia', currency: 'ETB', flag: '🇪🇹' },
    { code: 'ER', name: 'Eritrea', currency: 'ERN', flag: '🇪🇷' },
    { code: 'DJ', name: 'Djibouti', currency: 'DJF', flag: '🇩🇯' },
    { code: 'SO', name: 'Somalia', currency: 'SOS', flag: '🇸🇴' },
    { code: 'KE', name: 'Kenya', currency: 'KES', flag: '🇰🇪' },
    { code: 'TZ', name: 'Tanzania', currency: 'TZS', flag: '🇹🇿' },
    { code: 'UG', name: 'Uganda', currency: 'UGX', flag: '🇺🇬' },
    { code: 'RW', name: 'Rwanda', currency: 'RWF', flag: '🇷🇼' },
    { code: 'BI', name: 'Burundi', currency: 'BIF', flag: '🇧🇮' },
    { code: 'MG', name: 'Madagascar', currency: 'MGA', flag: '🇲🇬' },
    { code: 'MZ', name: 'Mozambique', currency: 'MZN', flag: '🇲🇿' },
    { code: 'ZW', name: 'Zimbabwe', currency: 'ZWL', flag: '🇿🇼' },
    { code: 'BW', name: 'Botswana', currency: 'BWP', flag: '🇧🇼' },
    { code: 'NA', name: 'Namibia', currency: 'NAD', flag: '🇳🇦' },
    { code: 'ZA', name: 'South Africa', currency: 'ZAR', flag: '🇿🇦' },
    { code: 'LS', name: 'Lesotho', currency: 'LSL', flag: '🇱🇸' },
    { code: 'SZ', name: 'Eswatini', currency: 'SZL', flag: '🇸🇿' },
    { code: 'AO', name: 'Angola', currency: 'AOA', flag: '🇦🇴' },
    { code: 'ZM', name: 'Zambia', currency: 'ZMW', flag: '🇿🇲' },
    { code: 'MW', name: 'Malawi', currency: 'MWK', flag: '🇲🇼' },
    { code: 'MU', name: 'Mauritius', currency: 'MUR', flag: '🇲🇺' },
    { code: 'SC', name: 'Seychelles', currency: 'SCR', flag: '🇸🇨' },
    { code: 'CV', name: 'Cape Verde', currency: 'CVE', flag: '🇨🇻' },
    { code: 'GN', name: 'Guinea', currency: 'GNF', flag: '🇬🇳' },
    { code: 'SL', name: 'Sierra Leone', currency: 'SLL', flag: '🇸🇱' },
    { code: 'LR', name: 'Liberia', currency: 'LRD', flag: '🇱🇷' },
    { code: 'MR', name: 'Mauritania', currency: 'MRU', flag: '🇲🇷' },
    { code: 'GM', name: 'Gambia', currency: 'GMD', flag: '🇬🇲' },
    { code: 'TG', name: 'Togo', currency: 'XOF', flag: '🇹🇬' },
    { code: 'BJ', name: 'Benin', currency: 'XOF', flag: '🇧🇯' },
    { code: 'ST', name: 'São Tomé and Príncipe', currency: 'STN', flag: '🇸🇹' },
    { code: 'GQ', name: 'Equatorial Guinea', currency: 'XAF', flag: '🇬🇶' },
    { code: 'KM', name: 'Comoros', currency: 'KMF', flag: '🇰🇲' },
    { code: 'CO', name: 'Colombia', currency: 'COP', flag: '🇨🇴' },
    { code: 'VE', name: 'Venezuela', currency: 'VED', flag: '🇻🇪' },
    { code: 'GY', name: 'Guyana', currency: 'GYD', flag: '🇬🇾' },
    { code: 'SR', name: 'Suriname', currency: 'SRD', flag: '🇸🇷' },
    { code: 'BO', name: 'Bolivia', currency: 'BOB', flag: '🇧🇴' },
    { code: 'PY', name: 'Paraguay', currency: 'PYG', flag: '🇵🇾' },
    { code: 'UY', name: 'Uruguay', currency: 'UYU', flag: '🇺🇾' },
    { code: 'AR', name: 'Argentina', currency: 'ARS', flag: '🇦🇷' },
    { code: 'CL', name: 'Chile', currency: 'CLP', flag: '🇨🇱' },
    { code: 'PE', name: 'Peru', currency: 'PEN', flag: '🇵🇪' },
    { code: 'EC', name: 'Ecuador', currency: 'USD', flag: '🇪🇨' },
    { code: 'CR', name: 'Costa Rica', currency: 'CRC', flag: '🇨🇷' },
    { code: 'PA', name: 'Panama', currency: 'PAB', flag: '🇵🇦' },
    { code: 'NI', name: 'Nicaragua', currency: 'NIO', flag: '🇳🇮' },
    { code: 'HN', name: 'Honduras', currency: 'HNL', flag: '🇭🇳' },
    { code: 'GT', name: 'Guatemala', currency: 'GTQ', flag: '🇬🇹' },
    { code: 'BZ', name: 'Belize', currency: 'BZD', flag: '🇧🇿' },
    { code: 'SV', name: 'El Salvador', currency: 'USD', flag: '🇸🇻' },
    { code: 'CU', name: 'Cuba', currency: 'CUP', flag: '🇨🇺' },
    { code: 'JM', name: 'Jamaica', currency: 'JMD', flag: '🇯🇲' },
    { code: 'TT', name: 'Trinidad and Tobago', currency: 'TTD', flag: '🇹🇹' },
    { code: 'BB', name: 'Barbados', currency: 'BBD', flag: '🇧🇧' },
    { code: 'LC', name: 'Saint Lucia', currency: 'XCD', flag: '🇱🇨' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', currency: 'XCD', flag: '🇻🇨' },
    { code: 'GD', name: 'Grenada', currency: 'XCD', flag: '🇬🇩' },
    { code: 'AG', name: 'Antigua and Barbuda', currency: 'XCD', flag: '🇦🇬' },
    { code: 'KN', name: 'Saint Kitts and Nevis', currency: 'XCD', flag: '🇰🇳' },
    { code: 'DM', name: 'Dominica', currency: 'XCD', flag: '🇩🇲' },
    { code: 'BS', name: 'Bahamas', currency: 'BSD', flag: '🇧🇸' },
    { code: 'HT', name: 'Haiti', currency: 'HTG', flag: '🇭🇹' },
    { code: 'DO', name: 'Dominican Republic', currency: 'DOP', flag: '🇩🇴' },
  ]);

  const getCountry = (code: string) => {
    return countries.value.find(country => country.code === code);
  };

  const list = computed(() => {
    return countries.value.map(country => ({
      value: country.code,
      label: `${country.flag} ${country.name} (${country.currency})`
    }));
  });

  const commonCorridors = () => {
    return [
      { from: 'US', to: 'IN' },
      { from: 'US', to: 'MX' },
      { from: 'US', to: 'PH' },
      { from: 'UK', to: 'IN' },
      { from: 'CA', to: 'IN' },
      { from: 'AU', to: 'IN' },
      { from: 'US', to: 'NG' },
      { from: 'UK', to: 'NG' },
    ];
  };

  return {
    countries,
    getCountry,
    list,
    commonCorridors,
  };
};

export const useCountry = (code: string) => {
  return useLazyAsyncData(`country-${code}`, async () => {
    // Mock country data
    return {
      code,
      name: code === 'US' ? 'United States' : code === 'UK' ? 'United Kingdom' : 'Country',
      currency: 'USD',
      providers: 15,
      avgTransferTime: '1-2 business days',
      bankingHours: '9:00 AM - 5:00 PM',
      weekendProcessing: 'Limited',
    };
  });
};
