import { PROVIDER_SCORES, getProviderScore } from '~/lib/providerScores'

export const useProviders = (filters?: any) => {
  return useLazyAsyncData('providers', async () => {
    // Mock providers data
    return [
      {
        id: 'wise',
        name: 'Wise',
        slug: 'wise',
        score: getProviderScore('wise')?.remitScore || 9.3,
        tagline: 'Best for transparency',
        speed: 'Instant - 2 days',
        rating: 4.8,
        reviewCount: 125000,
        description: 'Fast, cheap international money transfers with real exchange rates.',
        countries: 80,
        featured: true,
        features: ['Real exchange rates', 'Multi-currency account', 'Transparent pricing'],
        deliveryMethods: ['Bank Transfer', 'Mobile Wallet', 'Card Deposit'],
        affiliateUrl: 'https://wise.com',
        url: 'https://wise.com',
      },
      {
        id: 'remitly',
        name: 'Remitly',
        slug: 'remitly',
        score: getProviderScore('remitly')?.remitScore || 9.1,
        tagline: 'Best for speed',
        speed: '15 minutes',
        rating: 4.6,
        reviewCount: 45000,
        description: 'Express delivery to 135+ countries with 24/7 support.',
        countries: 135,
        featured: true,
        features: ['Express delivery', 'Cash pickup network', '24/7 support'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet', 'Home Delivery', 'Card Deposit'],
        affiliateUrl: 'https://remitly.com',
        url: 'https://remitly.com',
      },
      {
        id: 'xe-money',
        name: 'XE Money',
        slug: 'xe-money',
        score: getProviderScore('xe-money')?.remitScore || 8.7,
        tagline: 'Best for large amounts',
        speed: '1-4 days',
        rating: 4.5,
        reviewCount: 32000,
        description: 'Currency expertise with rate alerts and business accounts.',
        countries: 130,
        featured: false,
        features: ['Rate alerts', 'Currency expertise', 'Business accounts'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet'],
        affiliateUrl: 'https://xe.com',
        url: 'https://xe.com',
      },
      {
        id: 'xoom',
        name: 'Xoom',
        slug: 'xoom',
        score: getProviderScore('xoom')?.remitScore || 8.5,
        tagline: 'PayPal powered',
        speed: 'Minutes - 4 days',
        rating: 4.1,
        reviewCount: 56000,
        description: 'PayPal integration with bill payments and mobile reloads.',
        countries: 130,
        featured: false,
        features: ['PayPal integration', 'Bill payments', 'Mobile reloads'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet', 'Home Delivery', 'Card Deposit', 'Airtime Topup'],
        affiliateUrl: 'https://xoom.com',
        url: 'https://xoom.com',
      },
      {
        id: 'instarem',
        name: 'Instarem',
        slug: 'instarem',
        score: getProviderScore('instarem')?.remitScore || 8.4,
        tagline: 'Best for Asia',
        speed: '30 min - 2 days',
        rating: 4.3,
        reviewCount: 28000,
        description: 'Specialist in Asian corridors with business solutions.',
        countries: 55,
        featured: false,
        features: ['Asian corridors', 'Business solutions', 'Rate predictions'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet'],
        affiliateUrl: 'https://instarem.com',
        url: 'https://instarem.com',
      },
      {
        id: 'koronapay',
        name: 'KoronaPay',
        slug: 'koronapay',
        score: getProviderScore('koronapay')?.remitScore || 8.3,
        tagline: 'Extensive cash network',
        speed: 'Minutes - 24h',
        rating: 4.2,
        reviewCount: 19000,
        description: 'Extensive cash pickup network with global reach.',
        countries: 200,
        featured: false,
        features: ['Cash pickup', 'Store locations', 'Global reach'],
        deliveryMethods: ['Cash Pickup', 'Card Deposit', 'Bank Transfer'],
        affiliateUrl: 'https://koronapay.com',
        url: 'https://koronapay.com',
      },
      {
        id: 'transfergo',
        name: 'TransferGo',
        slug: 'transfergo',
        score: getProviderScore('transfergo')?.remitScore || 8.6,
        tagline: 'Best for Europe',
        speed: 'Instant available',
        rating: 4.4,
        reviewCount: 24000,
        description: 'European network with instant transfers available.',
        countries: 47,
        featured: false,
        features: ['Instant transfers', 'European network', 'Multiple speeds'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Card Deposit'],
        affiliateUrl: 'https://transfergo.com',
        url: 'https://transfergo.com',
      },
      {
        id: 'singx',
        name: 'SingX',
        slug: 'singx',
        score: 8.2,
        tagline: 'Best for Asia',
        speed: '1-4 days',
        rating: 4.1,
        reviewCount: 15000,
        description: 'Competitive rates with simple process for bank transfers.',
        countries: 50,
        featured: false,
        features: ['Bank transfers', 'Competitive rates', 'Simple process'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup'],
        affiliateUrl: 'https://singx.co',
        url: 'https://singx.co',
      },
      {
        id: 'paysend',
        name: 'Paysend',
        slug: 'paysend',
        score: getProviderScore('paysend')?.remitScore || 8.1,
        tagline: 'Card to card',
        speed: 'Minutes - 24h',
        rating: 4.0,
        reviewCount: 21000,
        description: 'Card-to-card transfers with fixed fees and simple process.',
        countries: 100,
        featured: false,
        features: ['Card transfers', 'Fixed fees', 'Simple process'],
        deliveryMethods: ['Bank Transfer', 'Card Deposit', 'Mobile Wallet', 'Cash Pickup'],
        affiliateUrl: 'https://paysend.com',
        url: 'https://paysend.com',
      },
      {
        id: 'sendwave',
        name: 'Sendwave',
        slug: 'sendwave',
        score: getProviderScore('sendwave')?.remitScore || 9.0,
        tagline: 'Best for Africa',
        speed: 'Instant',
        rating: 4.7,
        reviewCount: 18000,
        description: 'No transfer fees with instant mobile money delivery.',
        countries: 20,
        featured: true,
        features: ['No transfer fees', 'Mobile money', 'Instant delivery'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet'],
        affiliateUrl: 'https://sendwave.com',
        url: 'https://sendwave.com',
      },
      {
        id: 'remitbee',
        name: 'RemitBee',
        slug: 'remitbee',
        score: getProviderScore('remitbee')?.remitScore || 8.3,
        tagline: 'Best from Canada',
        speed: '1-3 days',
        rating: 4.3,
        reviewCount: 12000,
        description: 'Canadian-focused service with competitive rates.',
        countries: 50,
        featured: false,
        features: ['Canadian focus', 'Competitive rates', 'Easy signup'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet', 'Home Delivery'],
        affiliateUrl: 'https://remitbee.com',
        url: 'https://remitbee.com',
      },
      {
        id: 'ria',
        name: 'RIA',
        slug: 'ria',
        score: getProviderScore('ria')?.remitScore || 8.0,
        tagline: 'Largest network',
        speed: 'Minutes - 24h',
        rating: 4.1,
        reviewCount: 67000,
        description: '490,000+ locations worldwide with cash pickup.',
        countries: 160,
        featured: false,
        features: ['490,000+ locations', 'Cash pickup', 'Store locations'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet'],
        affiliateUrl: 'https://riamoneytransfer.com',
        url: 'https://riamoneytransfer.com',
      },
      {
        id: 'wirebarley',
        name: 'WireBarley',
        slug: 'wirebarley',
        score: getProviderScore('wirebarley')?.remitScore || 8.2,
        tagline: 'Korean specialist',
        speed: '1-2 days',
        rating: 4.2,
        reviewCount: 9000,
        description: 'Specialist in Korean corridors with competitive rates.',
        countries: 30,
        featured: false,
        features: ['Korean corridors', 'Competitive rates', 'Mobile app'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet', 'Home Delivery'],
        affiliateUrl: 'https://wirebarley.com',
        url: 'https://wirebarley.com',
      },
      {
        id: 'mukuru',
        name: 'Mukuru',
        slug: 'mukuru',
        score: getProviderScore('mukuru')?.remitScore || 8.4,
        tagline: 'African expert',
        speed: 'Minutes - 24h',
        rating: 4.4,
        reviewCount: 16000,
        description: 'Local African expertise with mobile money and airtime.',
        countries: 20,
        featured: false,
        features: ['Local expertise', 'Mobile money', 'Airtime top-up'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet'],
        affiliateUrl: 'https://mukuru.com',
        url: 'https://mukuru.com',
      },
      {
        id: 'western-union',
        name: 'Western Union',
        slug: 'western-union',
        score: getProviderScore('western-union')?.remitScore || 8.2,
        tagline: 'Most locations',
        speed: 'Minutes',
        rating: 4.2,
        reviewCount: 89000,
        description: '550,000+ locations worldwide with instant cash pickup.',
        countries: 200,
        featured: false,
        features: ['550,000+ locations', 'Instant cash', 'Global reach'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet'],
        affiliateUrl: 'https://westernunion.com',
        url: 'https://westernunion.com',
      },
      {
        id: 'orbitremit',
        name: 'OrbitRemit',
        slug: 'orbitremit',
        score: getProviderScore('orbitremit')?.remitScore || 8.1,
        tagline: 'New Zealand focus',
        speed: '1-3 days',
        rating: 4.0,
        reviewCount: 7000,
        description: 'NZ/AU specialist with fixed fees and good rates.',
        countries: 39,
        featured: false,
        features: ['NZ/AU corridors', 'Fixed fees', 'Good rates'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet'],
        affiliateUrl: 'https://orbitremit.com',
        url: 'https://orbitremit.com',
      },
      {
        id: 'pangea',
        name: 'Pangea',
        slug: 'pangea',
        score: getProviderScore('pangea')?.remitScore || 8.3,
        tagline: 'US to Latin America',
        speed: 'Minutes - 3 days',
        rating: 4.2,
        reviewCount: 11000,
        description: 'Latin America specialist with bill payments.',
        countries: 15,
        featured: false,
        features: ['Latin America focus', 'Bill payments', 'Mobile app'],
        deliveryMethods: ['Bank Transfer', 'Card Deposit', 'Mobile Wallet', 'Cash Pickup', 'Bill Payment'],
        affiliateUrl: 'https://pangea.app',
        url: 'https://pangea.app',
      },
      {
        id: 'al-ansari-exchange',
        name: 'Al Ansari Exchange',
        slug: 'al-ansari-exchange',
        score: getProviderScore('al-ansari-exchange')?.remitScore || 7.9,
        tagline: 'Popular in Middle East',
        speed: 'Minutes',
        rating: 3.9,
        reviewCount: 8000,
        description: 'Secure and trusted cash pickup with global reach.',
        countries: 200,
        featured: false,
        features: ['Cash pickup', 'Secure & Trusted', 'Global reach'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet'],
        affiliateUrl: 'https://alansariexchange.com',
        url: 'https://alansariexchange.com',
      },
      {
        id: 'placid',
        name: 'Placid',
        slug: 'placid',
        score: getProviderScore('placid')?.remitScore || 8.2,
        tagline: 'US to Asia specialist',
        speed: '30 min - 2 days',
        rating: 4.1,
        reviewCount: 6000,
        description: 'Competitive rates for US to Asia transfers.',
        countries: 50,
        featured: false,
        features: ['Competitive rates', 'Bank transfers', 'Mobile app'],
        deliveryMethods: ['Bank Transfer', 'Cash Pickup', 'Mobile Wallet'],
        affiliateUrl: 'https://placid.app',
        url: 'https://placid.app',
      },
    ]
  })
}

export const useProvider = (slug: string) => {
  return useLazyAsyncData(`provider-${slug}`, async () => {
    // Mock provider data
    const providers = (await useProviders().data.value) || []
    return providers.find(p => p.slug === slug) || null
  })
}
