import type { Component } from 'vue'

import {
  ArrowsRightLeftIcon as ArrowsRightLeftIconOutline,
  ArrowDownIcon as ArrowDownIconOutline,
  ArrowLeftIcon as ArrowLeftIconOutline,
  ArrowDownTrayIcon as ArrowDownTrayIconOutline,
  ArrowRightIcon as ArrowRightIconOutline,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareIconOutline,
  ArrowTrendingUpIcon as ArrowTrendingUpIconOutline,
  ArrowUpIcon as ArrowUpIconOutline,
  BellAlertIcon as BellAlertIconOutline,
  BookOpenIcon as BookOpenIconOutline,
  BoltIcon as BoltIconOutline,
  BookmarkIcon as BookmarkIconOutline,
  BuildingLibraryIcon as BuildingLibraryIconOutline,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightIconOutline,
  ChartBarIcon as ChartBarIconOutline,
  CheckIcon as CheckIconOutline,
  CheckCircleIcon as CheckCircleIconOutline,
  ChevronDownIcon as ChevronDownIconOutline,
  ChevronLeftIcon as ChevronLeftIconOutline,
  ChevronRightIcon as ChevronRightIconOutline,
  ChevronUpDownIcon as ChevronUpDownIconOutline,
  ChevronUpIcon as ChevronUpIconOutline,
  ClockIcon as ClockIconOutline,
  ComputerDesktopIcon as ComputerDesktopIconOutline,
  CreditCardIcon as CreditCardIconOutline,
  CurrencyDollarIcon as CurrencyDollarIconOutline,
  DocumentTextIcon as DocumentTextIconOutline,
  DocumentDuplicateIcon as DocumentDuplicateIconOutline,
  EyeIcon as EyeIconOutline,
  EnvelopeIcon as EnvelopeIconOutline,
  ExclamationTriangleIcon as ExclamationTriangleIconOutline,
  InformationCircleIcon as InformationCircleIconOutline,
  LockClosedIcon as LockClosedIconOutline,
  MagnifyingGlassIcon as MagnifyingGlassIconOutline,
  PencilSquareIcon as PencilSquareIconOutline,
  PlusIcon as PlusIconOutline,
  ShareIcon as ShareIconOutline,
  ShieldCheckIcon as ShieldCheckIconOutline,
  SignalIcon as SignalIconOutline,
  SparklesIcon as SparklesIconOutline,
  TrashIcon as TrashIconOutline,
  UserGroupIcon as UserGroupIconOutline,
  UserIcon as UserIconOutline,
  UserPlusIcon as UserPlusIconOutline,
  XMarkIcon as XMarkIconOutline,
} from '@heroicons/vue/24/outline'

import {
  ArrowsRightLeftIcon as ArrowsRightLeftIconSolid,
  ArrowDownIcon as ArrowDownIconSolid,
  ArrowLeftIcon as ArrowLeftIconSolid,
  ArrowDownTrayIcon as ArrowDownTrayIconSolid,
  ArrowRightIcon as ArrowRightIconSolid,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareIconSolid,
  ArrowTrendingUpIcon as ArrowTrendingUpIconSolid,
  ArrowUpIcon as ArrowUpIconSolid,
  BellAlertIcon as BellAlertIconSolid,
  BookOpenIcon as BookOpenIconSolid,
  BoltIcon as BoltIconSolid,
  BookmarkIcon as BookmarkIconSolid,
  BuildingLibraryIcon as BuildingLibraryIconSolid,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightIconSolid,
  ChartBarIcon as ChartBarIconSolid,
  CheckIcon as CheckIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  ChevronDownIcon as ChevronDownIconSolid,
  ChevronLeftIcon as ChevronLeftIconSolid,
  ChevronRightIcon as ChevronRightIconSolid,
  ChevronUpDownIcon as ChevronUpDownIconSolid,
  ChevronUpIcon as ChevronUpIconSolid,
  ClockIcon as ClockIconSolid,
  ComputerDesktopIcon as ComputerDesktopIconSolid,
  CreditCardIcon as CreditCardIconSolid,
  CurrencyDollarIcon as CurrencyDollarIconSolid,
  DocumentTextIcon as DocumentTextIconSolid,
  DocumentDuplicateIcon as DocumentDuplicateIconSolid,
  EyeIcon as EyeIconSolid,
  EnvelopeIcon as EnvelopeIconSolid,
  ExclamationTriangleIcon as ExclamationTriangleIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
  LockClosedIcon as LockClosedIconSolid,
  MagnifyingGlassIcon as MagnifyingGlassIconSolid,
  PencilSquareIcon as PencilSquareIconSolid,
  PlusIcon as PlusIconSolid,
  ShareIcon as ShareIconSolid,
  ShieldCheckIcon as ShieldCheckIconSolid,
  SignalIcon as SignalIconSolid,
  SparklesIcon as SparklesIconSolid,
  TrashIcon as TrashIconSolid,
  UserGroupIcon as UserGroupIconSolid,
  UserIcon as UserIconSolid,
  UserPlusIcon as UserPlusIconSolid,
  XMarkIcon as XMarkIconSolid,
} from '@heroicons/vue/24/solid'

export type IconVariant = 'outline' | 'solid'

export const ICONS_OUTLINE: Record<string, Component> = {
  'arrows-right-left': ArrowsRightLeftIconOutline,
  'arrow-down': ArrowDownIconOutline,
  'arrow-left': ArrowLeftIconOutline,
  'arrow-down-tray': ArrowDownTrayIconOutline,
  'arrow-right': ArrowRightIconOutline,
  'arrow-top-right': ArrowTopRightOnSquareIconOutline,
  'arrow-trending-up': ArrowTrendingUpIconOutline,
  'arrow-up': ArrowUpIconOutline,
  'bell-alert': BellAlertIconOutline,
  'book-open': BookOpenIconOutline,
  'bolt': BoltIconOutline,
  'bookmark': BookmarkIconOutline,
  'building-library': BuildingLibraryIconOutline,
  'chat-bubble': ChatBubbleLeftRightIconOutline,
  'chart-bar': ChartBarIconOutline,
  'check': CheckIconOutline,
  'check-circle': CheckCircleIconOutline,
  'chevron-down': ChevronDownIconOutline,
  'chevron-left': ChevronLeftIconOutline,
  'chevron-right': ChevronRightIconOutline,
  'chevron-up-down': ChevronUpDownIconOutline,
  'chevron-up': ChevronUpIconOutline,
  'clock': ClockIconOutline,
  'computer-desktop': ComputerDesktopIconOutline,
  'copy': DocumentDuplicateIconOutline,
  'credit-card': CreditCardIconOutline,
  'currency-dollar': CurrencyDollarIconOutline,
  'document-text': DocumentTextIconOutline,
  'eye': EyeIconOutline,
  'envelope': EnvelopeIconOutline,
  'exclamation-triangle': ExclamationTriangleIconOutline,
  'info': InformationCircleIconOutline,
  'lock': LockClosedIconOutline,
  'magnifying-glass': MagnifyingGlassIconOutline,
  'pencil-square': PencilSquareIconOutline,
  'plus': PlusIconOutline,
  'share': ShareIconOutline,
  'shield-check': ShieldCheckIconOutline,
  'signal': SignalIconOutline,
  'sparkles': SparklesIconOutline,
  'trash': TrashIconOutline,
  'user': UserIconOutline,
  'user-group': UserGroupIconOutline,
  'user-plus': UserPlusIconOutline,
  'x': XMarkIconOutline,
}

export const ICONS_SOLID: Record<string, Component> = {
  'arrows-right-left': ArrowsRightLeftIconSolid,
  'arrow-down': ArrowDownIconSolid,
  'arrow-left': ArrowLeftIconSolid,
  'arrow-down-tray': ArrowDownTrayIconSolid,
  'arrow-right': ArrowRightIconSolid,
  'arrow-top-right': ArrowTopRightOnSquareIconSolid,
  'arrow-trending-up': ArrowTrendingUpIconSolid,
  'arrow-up': ArrowUpIconSolid,
  'bell-alert': BellAlertIconSolid,
  'book-open': BookOpenIconSolid,
  'bolt': BoltIconSolid,
  'bookmark': BookmarkIconSolid,
  'building-library': BuildingLibraryIconSolid,
  'chat-bubble': ChatBubbleLeftRightIconSolid,
  'chart-bar': ChartBarIconSolid,
  'check': CheckIconSolid,
  'check-circle': CheckCircleIconSolid,
  'chevron-down': ChevronDownIconSolid,
  'chevron-left': ChevronLeftIconSolid,
  'chevron-right': ChevronRightIconSolid,
  'chevron-up-down': ChevronUpDownIconSolid,
  'chevron-up': ChevronUpIconSolid,
  'clock': ClockIconSolid,
  'computer-desktop': ComputerDesktopIconSolid,
  'copy': DocumentDuplicateIconSolid,
  'credit-card': CreditCardIconSolid,
  'currency-dollar': CurrencyDollarIconSolid,
  'document-text': DocumentTextIconSolid,
  'eye': EyeIconSolid,
  'envelope': EnvelopeIconSolid,
  'exclamation-triangle': ExclamationTriangleIconSolid,
  'info': InformationCircleIconSolid,
  'lock': LockClosedIconSolid,
  'magnifying-glass': MagnifyingGlassIconSolid,
  'pencil-square': PencilSquareIconSolid,
  'plus': PlusIconSolid,
  'share': ShareIconSolid,
  'shield-check': ShieldCheckIconSolid,
  'signal': SignalIconSolid,
  'sparkles': SparklesIconSolid,
  'trash': TrashIconSolid,
  'user': UserIconSolid,
  'user-group': UserGroupIconSolid,
  'user-plus': UserPlusIconSolid,
  'x': XMarkIconSolid,
}

export type IconName = keyof typeof ICONS_OUTLINE
