type CurrencyOption = {
  country: string
  currency: string
}

const INSTAREM_SOURCE_OPTIONS: CurrencyOption[] = [
  { country: 'HK', currency: 'USD' },
  { country: 'HU', currency: 'EUR' },
  { country: 'HR', currency: 'EUR' },
  { country: 'MY', currency: 'MYR' },
  { country: 'HK', currency: 'HKD' },
  { country: 'US', currency: 'USD' },
  { country: 'MT', currency: 'EUR' },
  { country: 'SI', currency: 'EUR' },
  { country: 'GR', currency: 'EUR' },
  { country: 'IE', currency: 'EUR' },
  { country: 'GB', currency: 'GBP' },
  { country: 'IT', currency: 'EUR' },
  { country: 'NO', currency: 'EUR' },
  { country: 'BG', currency: 'EUR' },
  { country: 'SG', currency: 'SGD' },
  { country: 'FI', currency: 'EUR' },
  { country: 'AT', currency: 'EUR' },
  { country: 'EE', currency: 'EUR' },
  { country: 'LV', currency: 'EUR' },
  { country: 'MY', currency: 'USD' },
  { country: 'IS', currency: 'EUR' },
  { country: 'NL', currency: 'EUR' },
  { country: 'DK', currency: 'EUR' },
  { country: 'RO', currency: 'EUR' },
  { country: 'SK', currency: 'EUR' },
  { country: 'LT', currency: 'EUR' },
  { country: 'ES', currency: 'EUR' },
  { country: 'FR', currency: 'EUR' },
  { country: 'SE', currency: 'EUR' },
  { country: 'DE', currency: 'EUR' },
  { country: 'CA', currency: 'CAD' },
  { country: 'SG', currency: 'USD' },
  { country: 'LU', currency: 'EUR' },
  { country: 'CZ', currency: 'EUR' },
  { country: 'PT', currency: 'EUR' },
  { country: 'AU', currency: 'AUD' },
  { country: 'BE', currency: 'EUR' },
  { country: 'PL', currency: 'EUR' },
  { country: 'IN', currency: 'INR' },
  { country: 'LI', currency: 'EUR' },
  { country: 'CY', currency: 'EUR' },
  { country: 'JP', currency: 'JPY' },
]

const INSTAREM_DESTINATION_OPTIONS: CurrencyOption[] = [
  { country: 'AR', currency: 'ARS' },
  { country: 'AU', currency: 'AUD' },
  { country: 'AU', currency: 'USD' },
  { country: 'AT', currency: 'EUR' },
  { country: 'AT', currency: 'USD' },
  { country: 'BD', currency: 'BDT' },
  { country: 'BD', currency: 'USD' },
  { country: 'BE', currency: 'EUR' },
  { country: 'BE', currency: 'USD' },
  { country: 'BT', currency: 'USD' },
  { country: 'BR', currency: 'BRL' },
  { country: 'BG', currency: 'EUR' },
  { country: 'BG', currency: 'USD' },
  { country: 'CA', currency: 'CAD' },
  { country: 'CA', currency: 'USD' },
  { country: 'CL', currency: 'CLP' },
  { country: 'CN', currency: 'CNY' },
  { country: 'CN', currency: 'USD' },
  { country: 'CO', currency: 'COP' },
  { country: 'HR', currency: 'EUR' },
  { country: 'HR', currency: 'USD' },
  { country: 'CY', currency: 'EUR' },
  { country: 'CY', currency: 'USD' },
  { country: 'CZ', currency: 'EUR' },
  { country: 'CZ', currency: 'USD' },
  { country: 'DK', currency: 'EUR' },
  { country: 'DK', currency: 'USD' },
  { country: 'DO', currency: 'DOP' },
  { country: 'EE', currency: 'EUR' },
  { country: 'EE', currency: 'USD' },
  { country: 'FI', currency: 'EUR' },
  { country: 'FI', currency: 'USD' },
  { country: 'FR', currency: 'EUR' },
  { country: 'FR', currency: 'USD' },
  { country: 'DE', currency: 'EUR' },
  { country: 'DE', currency: 'USD' },
  { country: 'GH', currency: 'GHS' },
  { country: 'GR', currency: 'EUR' },
  { country: 'GR', currency: 'USD' },
  { country: 'GT', currency: 'GTQ' },
  { country: 'HK', currency: 'HKD' },
  { country: 'HK', currency: 'USD' },
  { country: 'HU', currency: 'EUR' },
  { country: 'HU', currency: 'USD' },
  { country: 'IS', currency: 'EUR' },
  { country: 'IS', currency: 'USD' },
  { country: 'IN', currency: 'INR' },
  { country: 'IN', currency: 'USD' },
  { country: 'ID', currency: 'IDR' },
  { country: 'ID', currency: 'USD' },
  { country: 'IE', currency: 'EUR' },
  { country: 'IE', currency: 'USD' },
  { country: 'IT', currency: 'EUR' },
  { country: 'IT', currency: 'USD' },
  { country: 'JP', currency: 'USD' },
  { country: 'KE', currency: 'KES' },
  { country: 'LV', currency: 'EUR' },
  { country: 'LV', currency: 'USD' },
  { country: 'LT', currency: 'EUR' },
  { country: 'LT', currency: 'USD' },
  { country: 'LU', currency: 'EUR' },
  { country: 'LU', currency: 'USD' },
  { country: 'MY', currency: 'MYR' },
  { country: 'MY', currency: 'USD' },
  { country: 'MT', currency: 'EUR' },
  { country: 'MT', currency: 'USD' },
  { country: 'MX', currency: 'MXN' },
  { country: 'MC', currency: 'EUR' },
  { country: 'MC', currency: 'USD' },
  { country: 'NP', currency: 'NPR' },
  { country: 'NP', currency: 'USD' },
  { country: 'NL', currency: 'EUR' },
  { country: 'NL', currency: 'USD' },
  { country: 'NZ', currency: 'USD' },
  { country: 'NG', currency: 'NGN' },
  { country: 'NO', currency: 'EUR' },
  { country: 'NO', currency: 'USD' },
  { country: 'PK', currency: 'PKR' },
  { country: 'PE', currency: 'PEN' },
  { country: 'PH', currency: 'PHP' },
  { country: 'PH', currency: 'USD' },
  { country: 'PL', currency: 'EUR' },
  { country: 'PL', currency: 'USD' },
  { country: 'PT', currency: 'EUR' },
  { country: 'PT', currency: 'USD' },
  { country: 'RO', currency: 'EUR' },
  { country: 'RO', currency: 'USD' },
  { country: 'SM', currency: 'EUR' },
  { country: 'SM', currency: 'USD' },
  { country: 'SG', currency: 'SGD' },
  { country: 'SG', currency: 'USD' },
  { country: 'SK', currency: 'EUR' },
  { country: 'SK', currency: 'USD' },
  { country: 'SI', currency: 'EUR' },
  { country: 'SI', currency: 'USD' },
  { country: 'KR', currency: 'KRW' },
  { country: 'ES', currency: 'EUR' },
  { country: 'ES', currency: 'USD' },
  { country: 'LK', currency: 'LKR' },
  { country: 'LK', currency: 'USD' },
  { country: 'SE', currency: 'EUR' },
  { country: 'SE', currency: 'USD' },
  { country: 'CH', currency: 'USD' },
  { country: 'TH', currency: 'THB' },
  { country: 'TH', currency: 'USD' },
  { country: 'TR', currency: 'TRY' },
  { country: 'UG', currency: 'UGX' },
  { country: 'GB', currency: 'EUR' },
  { country: 'GB', currency: 'GBP' },
  { country: 'GB', currency: 'USD' },
  { country: 'UY', currency: 'UYU' },
  { country: 'VN', currency: 'USD' },
  { country: 'VN', currency: 'VND' },
]

export const INSTAREM_SOURCE_COUNTRIES = [
  'AT',
  'AU',
  'BE',
  'BG',
  'CA',
  'CY',
  'CZ',
  'DE',
  'DK',
  'EE',
  'ES',
  'FI',
  'FR',
  'GB',
  'GR',
  'HK',
  'HR',
  'HU',
  'IE',
  'IN',
  'IS',
  'IT',
  'JP',
  'LI',
  'LT',
  'LU',
  'LV',
  'MT',
  'MY',
  'NL',
  'NO',
  'PL',
  'PT',
  'RO',
  'SE',
  'SG',
  'SI',
  'SK',
  'US',
]

export const INSTAREM_DESTINATION_COUNTRIES = [
  'AR',
  'AT',
  'AU',
  'BD',
  'BE',
  'BG',
  'BR',
  'BT',
  'CA',
  'CH',
  'CL',
  'CN',
  'CO',
  'CY',
  'CZ',
  'DE',
  'DK',
  'DO',
  'EE',
  'ES',
  'FI',
  'FR',
  'GB',
  'GH',
  'GR',
  'GT',
  'HK',
  'HR',
  'HU',
  'ID',
  'IE',
  'IN',
  'IS',
  'IT',
  'JP',
  'KE',
  'KR',
  'LK',
  'LT',
  'LU',
  'LV',
  'MC',
  'MT',
  'MX',
  'MY',
  'NG',
  'NL',
  'NO',
  'NP',
  'NZ',
  'PE',
  'PH',
  'PK',
  'PL',
  'PT',
  'RO',
  'SE',
  'SG',
  'SI',
  'SK',
  'SM',
  'TH',
  'TR',
  'UG',
  'UY',
  'VN',
]

const buildSupportedCorridors = () => {
  const corridorSet = new Set<string>()
  for (const source of INSTAREM_SOURCE_OPTIONS) {
    for (const destination of INSTAREM_DESTINATION_OPTIONS) {
      if (source.country === destination.country) continue
      corridorSet.add(
        `${source.country}-${destination.country}-${source.currency}-${destination.currency}`,
      )
    }
  }
  return Array.from(corridorSet)
}

export const INSTAREM_SUPPORTED_CORRIDORS = buildSupportedCorridors()
export const INSTAREM_B2B_CORRIDORS = INSTAREM_SUPPORTED_CORRIDORS
