export interface Country {
  name: string
  code: string
  flag: string
  currency: string
}

export interface Currency {
  code: string
  name: string
  symbol: string
  countries: string[]
}

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', currency: 'AFN' },
  { name: 'Albania', code: 'AL', flag: '🇦🇱', currency: 'ALL' },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿', currency: 'DZD' },
  { name: 'American Samoa', code: 'AS', flag: '🇦🇸', currency: 'USD' },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩', currency: 'EUR' },
  { name: 'Angola', code: 'AO', flag: '🇦🇴', currency: 'AOA' },
  { name: 'Anguilla', code: 'AI', flag: '🇦🇮', currency: 'XCD' },
  { name: 'Antigua and Barbuda', code: 'AG', flag: '🇦🇬', currency: 'XCD' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷', currency: 'ARS' },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲', currency: 'AMD' },
  { name: 'Aruba', code: 'AW', flag: '🇦🇼', currency: 'AWG' },
  { name: 'Australia', code: 'AU', flag: '🇦🇺', currency: 'AUD' },
  { name: 'Austria', code: 'AT', flag: '🇦🇹', currency: 'EUR' },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', currency: 'AZN' },
  { name: 'Bahamas', code: 'BS', flag: '🇧🇸', currency: 'BSD' },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭', currency: 'BHD' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', currency: 'BDT' },
  { name: 'Barbados', code: 'BB', flag: '🇧🇧', currency: 'BBD' },
  { name: 'Belarus', code: 'BY', flag: '🇧🇾', currency: 'BYN' },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪', currency: 'EUR' },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿', currency: 'BZD' },
  { name: 'Benin', code: 'BJ', flag: '🇧🇯', currency: 'XOF' },
  { name: 'Bermuda', code: 'BM', flag: '🇧🇲', currency: 'BMD' },
  { name: 'Bhutan', code: 'BT', flag: '🇧🇹', currency: 'BTN' },
  { name: 'Bolivia', code: 'BO', flag: '🇧🇴', currency: 'BOB' },
  { name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦', currency: 'BAM' },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼', currency: 'BWP' },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷', currency: 'BRL' },
  { name: 'British Virgin Islands', code: 'VG', flag: '🇻🇬', currency: 'USD' },
  { name: 'Brunei', code: 'BN', flag: '🇧🇳', currency: 'BND' },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬', currency: 'BGN' },
  { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫', currency: 'XOF' },
  { name: 'Burundi', code: 'BI', flag: '🇧🇮', currency: 'BIF' },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭', currency: 'KHR' },
  { name: 'Cameroon', code: 'CM', flag: '🇨🇲', currency: 'XAF' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', currency: 'CAD' },
  { name: 'Cape Verde', code: 'CV', flag: '🇨🇻', currency: 'CVE' },
  { name: 'Cayman Islands', code: 'KY', flag: '🇰🇾', currency: 'KYD' },
  { name: 'Central African Republic', code: 'CF', flag: '🇨🇫', currency: 'XAF' },
  { name: 'Chad', code: 'TD', flag: '🇹🇩', currency: 'XAF' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱', currency: 'CLP' },
  { name: 'China', code: 'CN', flag: '🇨🇳', currency: 'CNY' },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴', currency: 'COP' },
  { name: 'Comoros', code: 'KM', flag: '🇰🇲', currency: 'KMF' },
  { name: 'Congo', code: 'CG', flag: '🇨🇬', currency: 'XAF' },
  { name: 'Congo (DRC)', code: 'CD', flag: '🇨🇩', currency: 'CDF' },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', currency: 'CRC' },
  { name: 'Côte d\'Ivoire', code: 'CI', flag: '🇨🇮', currency: 'XOF' },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷', currency: 'EUR' },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺', currency: 'CUP' },
  { name: 'Curaçao', code: 'CW', flag: '🇨🇼', currency: 'ANG' },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾', currency: 'EUR' },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿', currency: 'CZK' },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰', currency: 'DKK' },
  { name: 'Djibouti', code: 'DJ', flag: '🇩🇯', currency: 'DJF' },
  { name: 'Dominica', code: 'DM', flag: '🇩🇲', currency: 'XCD' },
  { name: 'Dominican Republic', code: 'DO', flag: '🇩🇴', currency: 'DOP' },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨', currency: 'USD' },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', currency: 'EGP' },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻', currency: 'USD' },
  { name: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶', currency: 'XAF' },
  { name: 'Eritrea', code: 'ER', flag: '🇪🇷', currency: 'ERN' },
  { name: 'Eswatini', code: 'SZ', flag: '🇸🇿', currency: 'SZL' },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', currency: 'ETB' },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯', currency: 'FJD' },
  { name: 'Finland', code: 'FI', flag: '🇫🇮', currency: 'EUR' },
  { name: 'France', code: 'FR', flag: '🇫🇷', currency: 'EUR' },
  { name: 'French Guiana', code: 'GF', flag: '🇬🇫', currency: 'EUR' },
  { name: 'French Polynesia', code: 'PF', flag: '🇵🇫', currency: 'XPF' },
  { name: 'Gabon', code: 'GA', flag: '🇬🇦', currency: 'XAF' },
  { name: 'Gambia', code: 'GM', flag: '🇬🇲', currency: 'GMD' },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪', currency: 'GEL' },
  { name: 'Germany', code: 'DE', flag: '🇩🇪', currency: 'EUR' },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', currency: 'GHS' },
  { name: 'Gibraltar', code: 'GI', flag: '🇬🇮', currency: 'GIP' },
  { name: 'Greece', code: 'GR', flag: '🇬🇷', currency: 'EUR' },
  { name: 'Greenland', code: 'GL', flag: '🇬🇱', currency: 'DKK' },
  { name: 'Grenada', code: 'GD', flag: '🇬🇩', currency: 'XCD' },
  { name: 'Guadeloupe', code: 'GP', flag: '🇬🇵', currency: 'EUR' },
  { name: 'Guam', code: 'GU', flag: '🇬🇺', currency: 'USD' },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹', currency: 'GTQ' },
  { name: 'Guinea', code: 'GN', flag: '🇬🇳', currency: 'GNF' },
  { name: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼', currency: 'XOF' },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾', currency: 'GYD' },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹', currency: 'HTG' },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳', currency: 'HNL' },
  { name: 'Hong Kong', code: 'HK', flag: '🇭🇰', currency: 'HKD' },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺', currency: 'HUF' },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸', currency: 'ISK' },
  { name: 'India', code: 'IN', flag: '🇮🇳', currency: 'INR' },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩', currency: 'IDR' },
  { name: 'Iran', code: 'IR', flag: '🇮🇷', currency: 'IRR' },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶', currency: 'IQD' },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪', currency: 'EUR' },
  { name: 'Israel', code: 'IL', flag: '🇮🇱', currency: 'ILS' },
  { name: 'Italy', code: 'IT', flag: '🇮🇹', currency: 'EUR' },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲', currency: 'JMD' },
  { name: 'Japan', code: 'JP', flag: '🇯🇵', currency: 'JPY' },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴', currency: 'JOD' },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', currency: 'KZT' },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', currency: 'KES' },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮', currency: 'AUD' },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼', currency: 'KWD' },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', currency: 'KGS' },
  { name: 'Laos', code: 'LA', flag: '🇱🇦', currency: 'LAK' },
  { name: 'Latvia', code: 'LV', flag: '🇱🇻', currency: 'EUR' },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧', currency: 'LBP' },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸', currency: 'LSL' },
  { name: 'Liberia', code: 'LR', flag: '🇱🇷', currency: 'LRD' },
  { name: 'Libya', code: 'LY', flag: '🇱🇾', currency: 'LYD' },
  { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮', currency: 'CHF' },
  { name: 'Lithuania', code: 'LT', flag: '🇱🇹', currency: 'EUR' },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', currency: 'EUR' },
  { name: 'Macau', code: 'MO', flag: '🇲🇴', currency: 'MOP' },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬', currency: 'MGA' },
  { name: 'Malawi', code: 'MW', flag: '🇲🇼', currency: 'MWK' },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾', currency: 'MYR' },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻', currency: 'MVR' },
  { name: 'Mali', code: 'ML', flag: '🇲🇱', currency: 'XOF' },
  { name: 'Malta', code: 'MT', flag: '🇲🇹', currency: 'EUR' },
  { name: 'Marshall Islands', code: 'MH', flag: '🇲🇭', currency: 'USD' },
  { name: 'Martinique', code: 'MQ', flag: '🇲🇶', currency: 'EUR' },
  { name: 'Mauritania', code: 'MR', flag: '🇲🇷', currency: 'MRU' },
  { name: 'Mauritius', code: 'MU', flag: '🇲🇺', currency: 'MUR' },
  { name: 'Mayotte', code: 'YT', flag: '🇾🇹', currency: 'EUR' },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽', currency: 'MXN' },
  { name: 'Micronesia', code: 'FM', flag: '🇫🇲', currency: 'USD' },
  { name: 'Moldova', code: 'MD', flag: '🇲🇩', currency: 'MDL' },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨', currency: 'EUR' },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳', currency: 'MNT' },
  { name: 'Montenegro', code: 'ME', flag: '🇲🇪', currency: 'EUR' },
  { name: 'Montserrat', code: 'MS', flag: '🇲🇸', currency: 'XCD' },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', currency: 'MAD' },
  { name: 'Mozambique', code: 'MZ', flag: '🇲🇿', currency: 'MZN' },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲', currency: 'MMK' },
  { name: 'Namibia', code: 'NA', flag: '🇳🇦', currency: 'NAD' },
  { name: 'Nauru', code: 'NR', flag: '🇳🇷', currency: 'AUD' },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵', currency: 'NPR' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱', currency: 'EUR' },
  { name: 'New Caledonia', code: 'NC', flag: '🇳🇨', currency: 'XPF' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', currency: 'NZD' },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', currency: 'NIO' },
  { name: 'Niger', code: 'NE', flag: '🇳🇪', currency: 'XOF' },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', currency: 'NGN' },
  { name: 'North Macedonia', code: 'MK', flag: '🇲🇰', currency: 'MKD' },
  { name: 'Norway', code: 'NO', flag: '🇳🇴', currency: 'NOK' },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', currency: 'OMR' },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', currency: 'PKR' },
  { name: 'Palau', code: 'PW', flag: '🇵🇼', currency: 'USD' },
  { name: 'Palestine', code: 'PS', flag: '🇵🇸', currency: 'ILS' },
  { name: 'Panama', code: 'PA', flag: '🇵🇦', currency: 'USD' },
  { name: 'Papua New Guinea', code: 'PG', flag: '🇵🇬', currency: 'PGK' },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾', currency: 'PYG' },
  { name: 'Peru', code: 'PE', flag: '🇵🇪', currency: 'PEN' },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭', currency: 'PHP' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱', currency: 'PLN' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', currency: 'EUR' },
  { name: 'Puerto Rico', code: 'PR', flag: '🇵🇷', currency: 'USD' },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', currency: 'QAR' },
  { name: 'Romania', code: 'RO', flag: '🇷🇴', currency: 'RON' },
  { name: 'Russia', code: 'RU', flag: '🇷🇺', currency: 'RUB' },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼', currency: 'RWF' },
  { name: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳', currency: 'XCD' },
  { name: 'Saint Lucia', code: 'LC', flag: '🇱🇨', currency: 'XCD' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', flag: '🇻🇨', currency: 'XCD' },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸', currency: 'WST' },
  { name: 'San Marino', code: 'SM', flag: '🇸🇲', currency: 'EUR' },
  { name: 'Sao Tome and Principe', code: 'ST', flag: '🇸🇹', currency: 'STN' },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', currency: 'SAR' },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳', currency: 'XOF' },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸', currency: 'RSD' },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨', currency: 'SCR' },
  { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱', currency: 'SLE' },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬', currency: 'SGD' },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰', currency: 'EUR' },
  { name: 'Slovenia', code: 'SI', flag: '🇸🇮', currency: 'EUR' },
  { name: 'Somalia', code: 'SO', flag: '🇸🇴', currency: 'SOS' },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', currency: 'ZAR' },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷', currency: 'KRW' },
  { name: 'Spain', code: 'ES', flag: '🇪🇸', currency: 'EUR' },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', currency: 'LKR' },
  { name: 'Sudan', code: 'SD', flag: '🇸🇩', currency: 'SDG' },
  { name: 'Suriname', code: 'SR', flag: '🇸🇷', currency: 'SRD' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪', currency: 'SEK' },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭', currency: 'CHF' },
  { name: 'Syria', code: 'SY', flag: '🇸🇾', currency: 'SYP' },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼', currency: 'TWD' },
  { name: 'Tajikistan', code: 'TJ', flag: '🇹🇯', currency: 'TJS' },
  { name: 'Tanzania', code: 'TZ', flag: '🇹🇿', currency: 'TZS' },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭', currency: 'THB' },
  { name: 'Timor-Leste', code: 'TL', flag: '🇹🇱', currency: 'USD' },
  { name: 'Togo', code: 'TG', flag: '🇹🇬', currency: 'XOF' },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴', currency: 'TOP' },
  { name: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹', currency: 'TTD' },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳', currency: 'TND' },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷', currency: 'TRY' },
  { name: 'Turkmenistan', code: 'TM', flag: '🇹🇲', currency: 'TMT' },
  { name: 'Tuvalu', code: 'TV', flag: '🇹🇻', currency: 'AUD' },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬', currency: 'UGX' },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦', currency: 'UAH' },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', currency: 'AED' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', currency: 'GBP' },
  { name: 'United States', code: 'US', flag: '🇺🇸', currency: 'USD' },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾', currency: 'UYU' },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', currency: 'UZS' },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺', currency: 'VUV' },
  { name: 'Vatican City', code: 'VA', flag: '🇻🇦', currency: 'EUR' },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪', currency: 'VES' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳', currency: 'VND' },
  { name: 'Wallis and Futuna', code: 'WF', flag: '🇼🇫', currency: 'XPF' },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪', currency: 'YER' },
  { name: 'Zambia', code: 'ZM', flag: '🇿🇲', currency: 'ZMW' },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', currency: 'ZWL' },
]

export const CURRENCIES: Record<string, Currency> = {
  USD: { code: 'USD', name: 'US Dollar', symbol: '$', countries: ['US'] },
  EUR: { code: 'EUR', name: 'Euro', symbol: '€', countries: ['DE', 'FR', 'IT', 'ES'] },
  GBP: { code: 'GBP', name: 'British Pound', symbol: '£', countries: ['GB'] },
  AFN: { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', countries: ['AF'] },
  ALL: { code: 'ALL', name: 'Albanian Lek', symbol: 'L', countries: ['AL'] },
  DZD: { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', countries: ['DZ'] },
  AOA: { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', countries: ['AO'] },
  XCD: { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', countries: ['AI', 'AG', 'DM', 'GD', 'MS', 'KN', 'LC', 'VC'] },
  ARS: { code: 'ARS', name: 'Argentine Peso', symbol: '$', countries: ['AR'] },
  AMD: { code: 'AMD', name: 'Armenian Dram', symbol: '֏', countries: ['AM'] },
  AWG: { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', countries: ['AW'] },
  AUD: { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', countries: ['AU'] },
  AZN: { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', countries: ['AZ'] },
  BSD: { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', countries: ['BS'] },
  BHD: { code: 'BHD', name: 'Bahraini Dinar', symbol: 'ب.د', countries: ['BH'] },
  BDT: { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', countries: ['BD'] },
  BBD: { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', countries: ['BB'] },
  BYN: { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', countries: ['BY'] },
  BZD: { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', countries: ['BZ'] },
  XOF: { code: 'XOF', name: 'West African CFA Franc', symbol: 'Fr', countries: ['BJ', 'BF', 'CI', 'GW', 'ML', 'NE', 'SN', 'TG'] },
  BMD: { code: 'BMD', name: 'Bermudian Dollar', symbol: '$', countries: ['BM'] },
  BTN: { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', countries: ['BT'] },
  BOB: { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', countries: ['BO'] },
  BAM: { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', countries: ['BA'] },
  BWP: { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', countries: ['BW'] },
  BRL: { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', countries: ['BR'] },
  BND: { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', countries: ['BN'] },
  BGN: { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', countries: ['BG'] },
  BIF: { code: 'BIF', name: 'Burundian Franc', symbol: 'Fr', countries: ['BI'] },
  KHR: { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', countries: ['KH'] },
  XAF: { code: 'XAF', name: 'Central African CFA Franc', symbol: 'Fr', countries: ['CM', 'CF', 'TD', 'CG', 'GQ', 'GA'] },
  CAD: { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', countries: ['CA'] },
  CVE: { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', countries: ['CV'] },
  KYD: { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', countries: ['KY'] },
  CLP: { code: 'CLP', name: 'Chilean Peso', symbol: '$', countries: ['CL'] },
  CNY: { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', countries: ['CN'] },
  COP: { code: 'COP', name: 'Colombian Peso', symbol: '$', countries: ['CO'] },
  KMF: { code: 'KMF', name: 'Comorian Franc', symbol: 'Fr', countries: ['KM'] },
  CDF: { code: 'CDF', name: 'Congolese Franc', symbol: 'Fr', countries: ['CD'] },
  CRC: { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', countries: ['CR'] },
  CUP: { code: 'CUP', name: 'Cuban Peso', symbol: '$', countries: ['CU'] },
  ANG: { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', countries: ['CW'] },
  CZK: { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', countries: ['CZ'] },
  DKK: { code: 'DKK', name: 'Danish Krone', symbol: 'kr', countries: ['DK'] },
  DJF: { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fr', countries: ['DJ'] },
  DOP: { code: 'DOP', name: 'Dominican Peso', symbol: '$', countries: ['DO'] },
  ERN: { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', countries: ['ER'] },
  SZL: { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L', countries: ['SZ'] },
  ETB: { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', countries: ['ET'] },
  FJD: { code: 'FJD', name: 'Fijian Dollar', symbol: '$', countries: ['FJ'] },
  XPF: { code: 'XPF', name: 'CFP Franc', symbol: '₣', countries: ['PF', 'NC', 'WF'] },
  GMD: { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', countries: ['GM'] },
  GEL: { code: 'GEL', name: 'Georgian Lari', symbol: '₾', countries: ['GE'] },
  GHS: { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', countries: ['GH'] },
  GIP: { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', countries: ['GI'] },
  GTQ: { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', countries: ['GT'] },
  GNF: { code: 'GNF', name: 'Guinean Franc', symbol: 'Fr', countries: ['GN'] },
  GYD: { code: 'GYD', name: 'Guyanese Dollar', symbol: '$', countries: ['GY'] },
  HTG: { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', countries: ['HT'] },
  HNL: { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', countries: ['HN'] },
  HKD: { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', countries: ['HK'] },
  HUF: { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', countries: ['HU'] },
  ISK: { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', countries: ['IS'] },
  INR: { code: 'INR', name: 'Indian Rupee', symbol: '₹', countries: ['IN'] },
  IDR: { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', countries: ['ID'] },
  IRR: { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', countries: ['IR'] },
  IQD: { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', countries: ['IQ'] },
  ILS: { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', countries: ['IL'] },
  JMD: { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', countries: ['JM'] },
  JPY: { code: 'JPY', name: 'Japanese Yen', symbol: '¥', countries: ['JP'] },
  JOD: { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', countries: ['JO'] },
  KZT: { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', countries: ['KZ'] },
  KES: { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', countries: ['KE'] },
  KWD: { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', countries: ['KW'] },
  KGS: { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с', countries: ['KG'] },
  LAK: { code: 'LAK', name: 'Lao Kip', symbol: '₭', countries: ['LA'] },
  LBP: { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', countries: ['LB'] },
  LSL: { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', countries: ['LS'] },
  LRD: { code: 'LRD', name: 'Liberian Dollar', symbol: '$', countries: ['LR'] },
  LYD: { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', countries: ['LY'] },
  CHF: { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', countries: ['CH', 'LI'] },
  MOP: { code: 'MOP', name: 'Macanese Pataca', symbol: 'P', countries: ['MO'] },
  MGA: { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', countries: ['MG'] },
  MWK: { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', countries: ['MW'] },
  MYR: { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', countries: ['MY'] },
  MVR: { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', countries: ['MV'] },
  MRU: { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', countries: ['MR'] },
  MUR: { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', countries: ['MU'] },
  MXN: { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', countries: ['MX'] },
  MDL: { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', countries: ['MD'] },
  MNT: { code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮', countries: ['MN'] },
  MAD: { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', countries: ['MA'] },
  MZN: { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', countries: ['MZ'] },
  MMK: { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', countries: ['MM'] },
  NAD: { code: 'NAD', name: 'Namibian Dollar', symbol: '$', countries: ['NA'] },
  NPR: { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', countries: ['NP'] },
  NZD: { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', countries: ['NZ'] },
  NIO: { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', countries: ['NI'] },
  NGN: { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', countries: ['NG'] },
  MKD: { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', countries: ['MK'] },
  NOK: { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', countries: ['NO'] },
  OMR: { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', countries: ['OM'] },
  PKR: { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', countries: ['PK'] },
  PGK: { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', countries: ['PG'] },
  PYG: { code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲', countries: ['PY'] },
  PEN: { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', countries: ['PE'] },
  PHP: { code: 'PHP', name: 'Philippine Peso', symbol: '₱', countries: ['PH'] },
  PLN: { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', countries: ['PL'] },
  QAR: { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', countries: ['QA'] },
  RON: { code: 'RON', name: 'Romanian Leu', symbol: 'lei', countries: ['RO'] },
  RUB: { code: 'RUB', name: 'Russian Ruble', symbol: '₽', countries: ['RU'] },
  RWF: { code: 'RWF', name: 'Rwandan Franc', symbol: 'Fr', countries: ['RW'] },
  WST: { code: 'WST', name: 'Samoan Tālā', symbol: 'T', countries: ['WS'] },
  STN: { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', countries: ['ST'] },
  SAR: { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', countries: ['SA'] },
  RSD: { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', countries: ['RS'] },
  SCR: { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', countries: ['SC'] },
  SLE: { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', countries: ['SL'] },
  SGD: { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', countries: ['SG'] },
  SOS: { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', countries: ['SO'] },
  ZAR: { code: 'ZAR', name: 'South African Rand', symbol: 'R', countries: ['ZA'] },
  KRW: { code: 'KRW', name: 'South Korean Won', symbol: '₩', countries: ['KR'] },
  LKR: { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', countries: ['LK'] },
  SDG: { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', countries: ['SD'] },
  SRD: { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', countries: ['SR'] },
  SEK: { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', countries: ['SE'] },
  SYP: { code: 'SYP', name: 'Syrian Pound', symbol: '£', countries: ['SY'] },
  TWD: { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', countries: ['TW'] },
  TJS: { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', countries: ['TJ'] },
  TZS: { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'Sh', countries: ['TZ'] },
  THB: { code: 'THB', name: 'Thai Baht', symbol: '฿', countries: ['TH'] },
  TOP: { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', countries: ['TO'] },
  TTD: { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: '$', countries: ['TT'] },
  TND: { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', countries: ['TN'] },
  TRY: { code: 'TRY', name: 'Turkish Lira', symbol: '₺', countries: ['TR'] },
  TMT: { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', countries: ['TM'] },
  UGX: { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', countries: ['UG'] },
  UAH: { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', countries: ['UA'] },
  AED: { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', countries: ['AE'] },
  UYU: { code: 'UYU', name: 'Uruguayan Peso', symbol: '$', countries: ['UY'] },
  UZS: { code: 'UZS', name: 'Uzbekistani Som', symbol: 'so\'m', countries: ['UZ'] },
  VUV: { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt', countries: ['VU'] },
  VES: { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.S', countries: ['VE'] },
  VND: { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', countries: ['VN'] },
  YER: { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', countries: ['YE'] },
  ZMW: { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', countries: ['ZM'] },
  ZWL: { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: '$', countries: ['ZW'] },
}

// Always available currencies
export const BASE_CURRENCIES = ['USD', 'GBP', 'EUR']

// Helper to get country by code
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code)
}

// Helper to get currency info
export function getCurrencyInfo(code: string): Currency | undefined {
  return CURRENCIES[code]
}

// Helper to get available currencies for a country
// Always includes USD, GBP, EUR plus the country's native currency
export function getAvailableCurrencies(countryCode: string): string[] {
  const country = getCountryByCode(countryCode)
  if (!country) return BASE_CURRENCIES

  const currencies = new Set([...BASE_CURRENCIES, country.currency])
  return Array.from(currencies)
}

// Get currency display name
export function getCurrencyDisplay(code: string): string {
  const currency = CURRENCIES[code]
  if (!currency) return code

  return `${code} | ${currency.name}`
}

// Get country display name
export function getCountryDisplay(code: string): string {
  const country = getCountryByCode(code)
  if (!country) return code

  return `${country.flag} ${country.name}`
}
