import type { Pool } from 'pg';
type PlacidCollectorOptions = {
    pool?: Pool;
    closePool?: boolean;
    corridors?: string[];
    delayMs?: number;
    jitterMs?: number;
    rateLimitBackoffMs?: number;
    rateLimitJitterMs?: number;
    rateLimitMaxRetries?: number;
    corridorDelayMs?: number;
    corridorJitterMs?: number;
    amountBuckets?: number[];
    payinMethod?: string;
    payoutMethod?: string;
    locale?: string;
    collectorType?: string;
    freshnessSloMinutes?: number;
    freshnessSloEnabled?: boolean;
    rpmOverride?: number;
    perCorridorRpmOverride?: number;
};
export declare const runPlacidCollector: (options?: PlacidCollectorOptions) => Promise<boolean>;
export {};
