"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.payoutMethods = exports.payinMethods = exports.corridorSource = exports.corridors = exports.defaultPayoutMethod = exports.defaultPayinMethod = exports.amountBuckets = void 0;
const amount_bucket_1 = require("../../../../shared/amount-bucket");
const supported_corridors_1 = require("./supported-corridors");
exports.amountBuckets = amount_bucket_1.DEFAULT_AMOUNT_BUCKETS;
exports.defaultPayinMethod = 'bank_transfer';
exports.defaultPayoutMethod = 'bank_deposit';
exports.corridors = supported_corridors_1.WELLSFARGO_SUPPORTED_CORRIDORS;
exports.corridorSource = 'provider_corridor_capability';
exports.payinMethods = ['bank_transfer'];
exports.payoutMethods = ['bank_deposit'];
