import { QualityFlag } from '../../normalize/quality-flags';
type WellsFargoPayload = {
    errorMessage?: string | null;
    informationMessage?: string | null;
    warningMessage?: string | null;
    responseCode?: string | null;
    receivingCountry?: string | null;
    rnm?: string | null;
    paymentMethod?: string | null;
    requestedAmount?: string | null;
    formattedDeliveyAmount?: string | null;
    formattedFxRate?: string | null;
    formattedTransferFeeString?: string | null;
    deliveryAmountCurrency?: string | null;
    fxCurrency?: string | null;
    transferFeeCurrency?: string | null;
    wibURL?: string | null;
    totalAmount?: string | null;
    specialOffers?: unknown;
    transferFeesMap?: Record<string, string> | null;
    fxRateMap?: Record<string, string> | null;
    invalidFields?: unknown;
    paymentTypes?: unknown;
    rnmMap?: unknown;
    paymentFromCashFlag?: boolean;
    deliveryAmountCurrencyFlag?: boolean;
    fxRateMapFlag?: boolean;
    paymentFromAccountFlag?: boolean;
    informationMessageMsgCode?: string | null;
    receivingCountryCode?: string | null;
    errorMessageMsgCode?: string | null;
    paymentMethodCode?: string | null;
    requestedRawAmount?: number;
    rnmCode?: string | null;
};
export type WellsFargoParsedQuote = {
    send_amount: number;
    receive_amount: number;
    fee_amount: number;
    total_debit_amount: number;
    payin_method: string;
    payout_method: string;
    fee_currency: string | null;
    promotional_fee_amount: number | null;
    promotional_rate: number | null;
    base_rate: number | null;
    promotional_cap_amount: number | null;
    delivery_time_min_minutes: number | null;
    delivery_time_max_minutes: number | null;
    collected_at: string;
    parser_version: string;
    parse_flags: QualityFlag[];
};
export declare const parseWellsFargoPayload: (payload: WellsFargoPayload) => WellsFargoParsedQuote | null;
export {};
