"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.payoutMethodMap = exports.payinMethodMap = exports.isXeCorridorSupported = exports.getXeCurrencyForCountry = exports.getSourceCountryForCurrency = exports.XE_CORRIDOR_PAIRS = exports.XE_COMMON_SOURCE_CURRENCIES = exports.XE_COUNTRY_TO_CURRENCY = exports.currencyCodeMap = exports.countryCodeMap = void 0;
const countries_currencies_1 = require("../../../../shared/countries-currencies");
exports.countryCodeMap = {};
exports.currencyCodeMap = {};
exports.XE_COUNTRY_TO_CURRENCY = {
    AD: 'EUR',
    AE: 'AED',
    AF: 'AFN',
    AG: 'XCD',
    AI: 'XCD',
    AL: 'ALL',
    AM: 'AMD',
    AO: 'AOA',
    AQ: 'USD',
    AR: 'ARS',
    AS: 'USD',
    AT: 'EUR',
    AU: 'AUD',
    AW: 'AWG',
    AZ: 'AZN',
    BA: 'BAM',
    BB: 'BBD',
    BD: 'BDT',
    BE: 'EUR',
    BF: 'XOF',
    BG: 'BGN',
    BH: 'BHD',
    BI: 'BIF',
    BJ: 'XOF',
    BM: 'BMD',
    BN: 'BND',
    BO: 'BOB',
    BR: 'BRL',
    BS: 'BSD',
    BT: 'BTN',
    BV: 'NOK',
    BW: 'BWP',
    BY: 'BYN',
    BZ: 'BZD',
    CA: 'CAD',
    CD: 'CDF',
    CF: 'XAF',
    CG: 'XAF',
    CH: 'CHF',
    CI: 'XOF',
    CK: 'NZD',
    CL: 'CLP',
    CM: 'XAF',
    CN: 'CNY',
    CO: 'COP',
    CR: 'CRC',
    CU: 'CUP',
    CV: 'CVE',
    CW: 'ANG',
    CY: 'EUR',
    CZ: 'CZK',
    DE: 'EUR',
    DJ: 'DJF',
    DK: 'DKK',
    DM: 'XCD',
    DO: 'DOP',
    DZ: 'DZD',
    EC: 'USD',
    EE: 'EUR',
    EG: 'EGP',
    EH: 'MAD',
    ER: 'ERN',
    ES: 'EUR',
    ET: 'ETB',
    FI: 'EUR',
    FJ: 'FJD',
    FK: 'FKP',
    FM: 'USD',
    FO: 'DKK',
    FR: 'EUR',
    GA: 'XAF',
    GB: 'GBP',
    GD: 'XCD',
    GE: 'GEL',
    GF: 'EUR',
    GG: 'GBP',
    GH: 'GHS',
    GI: 'GIP',
    GL: 'DKK',
    GM: 'GMD',
    GN: 'GNF',
    GP: 'EUR',
    GQ: 'XAF',
    GR: 'EUR',
    GT: 'GTQ',
    GU: 'USD',
    GW: 'XOF',
    GY: 'GYD',
    HK: 'HKD',
    HN: 'HNL',
    HR: 'EUR',
    HT: 'HTG',
    HU: 'HUF',
    ID: 'IDR',
    IE: 'EUR',
    IL: 'ILS',
    IM: 'GBP',
    IN: 'INR',
    IO: 'USD',
    IQ: 'IQD',
    IR: 'IRR',
    IS: 'ISK',
    IT: 'EUR',
    JE: 'GBP',
    JM: 'JMD',
    JO: 'JOD',
    JP: 'JPY',
    KE: 'KES',
    KG: 'KGS',
    KH: 'KHR',
    KI: 'AUD',
    KM: 'KMF',
    KN: 'XCD',
    KP: 'KPW',
    KR: 'KRW',
    KW: 'KWD',
    KY: 'KYD',
    KZ: 'KZT',
    LA: 'LAK',
    LB: 'LBP',
    LC: 'XCD',
    LI: 'CHF',
    LK: 'LKR',
    LR: 'LRD',
    LS: 'LSL',
    LT: 'EUR',
    LU: 'EUR',
    LV: 'EUR',
    LY: 'LYD',
    MA: 'MAD',
    MC: 'EUR',
    MD: 'MDL',
    ME: 'EUR',
    MF: 'EUR',
    MG: 'MGA',
    MH: 'USD',
    MK: 'MKD',
    ML: 'XOF',
    MM: 'MMK',
    MN: 'MNT',
    MO: 'MOP',
    MP: 'USD',
    MQ: 'EUR',
    MR: 'MRU',
    MS: 'XCD',
    MT: 'EUR',
    MU: 'MUR',
    MV: 'MVR',
    MW: 'MWK',
    MX: 'MXN',
    MY: 'MYR',
    MZ: 'MZN',
    NA: 'NAD',
    NC: 'XPF',
    NE: 'XOF',
    NF: 'AUD',
    NG: 'NGN',
    NI: 'NIO',
    NL: 'EUR',
    NO: 'NOK',
    NP: 'NPR',
    NR: 'AUD',
    NU: 'NZD',
    NZ: 'NZD',
    OM: 'OMR',
    PA: 'PAB',
    PE: 'PEN',
    PF: 'XPF',
    PG: 'PGK',
    PH: 'PHP',
    PK: 'PKR',
    PL: 'PLN',
    PM: 'EUR',
    PN: 'NZD',
    PR: 'USD',
    PS: 'ILS',
    PT: 'EUR',
    PW: 'USD',
    PY: 'PYG',
    QA: 'QAR',
    RE: 'EUR',
    RO: 'RON',
    RS: 'RSD',
    RU: 'RUB',
    RW: 'RWF',
    SA: 'SAR',
    SB: 'SBD',
    SC: 'SCR',
    SD: 'SDG',
    SE: 'SEK',
    SG: 'SGD',
    SH: 'SHP',
    SI: 'EUR',
    SJ: 'NOK',
    SK: 'EUR',
    SL: 'SLL',
    SM: 'EUR',
    SN: 'XOF',
    SO: 'SOS',
    SR: 'SRD',
    SS: 'SSP',
    ST: 'STN',
    SV: 'USD',
    SX: 'ANG',
    SY: 'SYP',
    SZ: 'SZL',
    TC: 'USD',
    TD: 'XAF',
    TF: 'EUR',
    TG: 'XOF',
    TH: 'THB',
    TJ: 'TJS',
    TK: 'NZD',
    TL: 'USD',
    TM: 'TMT',
    TN: 'TND',
    TO: 'TOP',
    TR: 'TRY',
    TT: 'TTD',
    TV: 'AUD',
    TW: 'TWD',
    TZ: 'TZS',
    UA: 'UAH',
    UG: 'UGX',
    US: 'USD',
    UY: 'UYU',
    UZ: 'UZS',
    VA: 'EUR',
    VC: 'XCD',
    VE: 'VES',
    VG: 'USD',
    VI: 'USD',
    VN: 'VND',
    VU: 'VUV',
    WF: 'XPF',
    WS: 'WST',
    XK: 'EUR',
    YE: 'YER',
    YT: 'EUR',
    ZA: 'ZAR',
    ZM: 'ZMW',
    ZW: 'ZWL',
};
exports.XE_COMMON_SOURCE_CURRENCIES = [
    'USD',
    'EUR',
    'GBP',
    'CAD',
    'AUD',
    'NZD',
    'JPY',
    'CHF',
    'SGD',
    'HKD',
];
exports.XE_CORRIDOR_PAIRS = [
    ['USD', 'IN'],
    ['USD', 'PH'],
    ['USD', 'PK'],
    ['USD', 'MX'],
    ['USD', 'DE'],
    ['USD', 'FR'],
    ['USD', 'ES'],
    ['USD', 'IT'],
    ['USD', 'AU'],
    ['USD', 'GB'],
    ['USD', 'CA'],
    ['USD', 'NZ'],
    ['USD', 'SG'],
    ['USD', 'AE'],
    ['USD', 'ZA'],
    ['USD', 'KE'],
    ['USD', 'NG'],
    ['USD', 'CN'],
    ['USD', 'JP'],
    ['USD', 'KR'],
    ['USD', 'TH'],
    ['USD', 'VN'],
    ['USD', 'ID'],
    ['USD', 'MY'],
    ['USD', 'TR'],
    ['USD', 'BR'],
    ['USD', 'CO'],
    ['EUR', 'PH'],
    ['EUR', 'IN'],
    ['EUR', 'PK'],
    ['EUR', 'MX'],
    ['EUR', 'US'],
    ['EUR', 'GB'],
    ['EUR', 'CA'],
    ['EUR', 'AU'],
    ['EUR', 'NZ'],
    ['EUR', 'ZA'],
    ['EUR', 'AE'],
    ['GBP', 'IN'],
    ['GBP', 'PK'],
    ['GBP', 'PH'],
    ['GBP', 'MX'],
    ['GBP', 'DE'],
    ['GBP', 'US'],
    ['GBP', 'CA'],
    ['GBP', 'AU'],
    ['GBP', 'NZ'],
    ['GBP', 'AE'],
    ['CAD', 'IN'],
    ['CAD', 'PK'],
    ['CAD', 'PH'],
    ['CAD', 'US'],
    ['CAD', 'GB'],
    ['CAD', 'AU'],
    ['CAD', 'NZ'],
    ['AUD', 'IN'],
    ['AUD', 'PH'],
    ['AUD', 'PK'],
    ['AUD', 'US'],
    ['AUD', 'GB'],
    ['AUD', 'CA'],
    ['AUD', 'NZ'],
    ['NZD', 'IN'],
    ['NZD', 'PH'],
    ['NZD', 'AU'],
    ['NZD', 'GB'],
    ['NZD', 'US'],
];
const XE_SOURCE_COUNTRY_BY_CURRENCY = {
    USD: 'US',
    EUR: 'DE',
    GBP: 'GB',
    CAD: 'CA',
    AUD: 'AU',
    NZD: 'NZ',
    JPY: 'JP',
    CHF: 'CH',
    SGD: 'SG',
    HKD: 'HK',
};
const findCountryForCurrency = (currency) => {
    const entries = Object.entries(exports.XE_COUNTRY_TO_CURRENCY);
    for (const [country, curr] of entries) {
        if (curr === currency)
            return country;
    }
    return null;
};
const getSourceCountryForCurrency = (currency) => {
    const code = currency.toUpperCase();
    return XE_SOURCE_COUNTRY_BY_CURRENCY[code] ?? findCountryForCurrency(code);
};
exports.getSourceCountryForCurrency = getSourceCountryForCurrency;
const getXeCurrencyForCountry = (countryCode) => {
    const code = countryCode.toUpperCase();
    return exports.XE_COUNTRY_TO_CURRENCY[code] ?? (0, countries_currencies_1.getCountryByCode)(code)?.currency ?? null;
};
exports.getXeCurrencyForCountry = getXeCurrencyForCountry;
const isXeCorridorSupported = (sourceCurrency, targetCountry) => {
    const source = sourceCurrency.toUpperCase();
    const target = targetCountry.toUpperCase();
    const explicit = exports.XE_CORRIDOR_PAIRS.some(([currency, country]) => currency === source && country === target);
    if (explicit)
        return true;
    if (exports.XE_COMMON_SOURCE_CURRENCIES.includes(source) && exports.XE_COUNTRY_TO_CURRENCY[target]) {
        return true;
    }
    return false;
};
exports.isXeCorridorSupported = isXeCorridorSupported;
exports.payinMethodMap = {
    bank_transfer: 'bank_transfer',
    bank: 'bank_transfer',
    bankaccount: 'bank_transfer',
    bank_account: 'bank_transfer',
    transfer: 'bank_transfer',
};
exports.payoutMethodMap = {
    bank_deposit: 'bank_deposit',
    bank: 'bank_deposit',
    bankaccount: 'bank_deposit',
    bank_account: 'bank_deposit',
    cash_pickup: 'cash_pickup',
    cash: 'cash_pickup',
    mobile_wallet: 'mobile_wallet',
    mobile: 'mobile_wallet',
    wallet: 'mobile_wallet',
};
