export declare const countryCodeMap: Record<string, string>;
export declare const currencyCodeMap: Record<string, string>;
export declare const XE_COUNTRY_TO_CURRENCY: Record<string, string>;
export declare const XE_COMMON_SOURCE_CURRENCIES: string[];
export declare const XE_CORRIDOR_PAIRS: Array<[string, string]>;
export declare const getSourceCountryForCurrency: (currency: string) => string | null;
export declare const getXeCurrencyForCountry: (countryCode: string) => string | null;
export declare const isXeCorridorSupported: (sourceCurrency: string, targetCountry: string) => boolean;
export declare const payinMethodMap: Record<string, string>;
export declare const payoutMethodMap: Record<string, string>;
