import type { ChartMetadata, ChartCategory } from '~/types/pulse'

export const CHART_CATEGORIES: Record<ChartCategory, { label: string, order: number }> = {
  'cost-markup': { label: 'Pricing & Margin', order: 1 },
  'delivered-amount': { label: 'Competitive Dynamics', order: 2 },
  'volatility': { label: 'Volatility & Risk', order: 3 },
  'availability': { label: 'Operational Coverage', order: 4 },
}

export const PROVIDER_COLORS: Record<string, string> = {
  wise: '#00b9ff',
  remitly: '#2ecc71',
  xe: '#9b59b6',
  ria: '#f43f5e',
  dahabshiil: '#ea580c',
  xoom: '#3498db',
  worldremit: '#e74c3c',
  sendwave: '#f39c12',
  westernunion: '#ffd700',
  koronapay: '#f59e0b',
  remitbee: '#3b82f6',
  bossmoney: '#2a2825',
  placid: '#16a34a',
  paypal: '#003087',
  revolut: '#0075eb',
  best: '#10b981',
}

export const pulseChartRegistry: ChartMetadata[] = [
  {
    id: 'all-in-cost',
    title: 'All-in Cost Index (RCI)',
    category: 'cost-markup',
    categoryLabel: 'Pricing & Margin',
    type: 'line',
    unit: 'percent',
    unitLabel: '%',
    description: 'Remittance Cost Index (RCI) from Gold indices for $500 bank transfers.',
    insightTemplate: 'RCI {direction} {delta}% this week',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount', 'payoutMethod'],
    tooltipCopy: 'RCI measures total cost (fees + FX markup) as a % of send amount.',
    sourceNotes: 'Gold indices · $500 bank bucket · updated daily',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'fx-markup',
    title: 'FX Markup vs Mid-Market (TEER-derived)',
    category: 'cost-markup',
    categoryLabel: 'Pricing & Margin',
    type: 'line',
    unit: 'bps',
    unitLabel: 'bps',
    description: 'Implied FX markup vs mid-market derived from TEER.',
    insightTemplate: 'Markup is {value} bps ({direction} {delta} bps vs 7d avg)',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount'],
    tooltipCopy: '1 basis point = 0.01%. Higher markup means worse pricing.',
    sourceNotes: 'Gold indices · $500 bank bucket · updated daily',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'fee-vs-markup',
    title: 'Fee vs Markup Decomposition',
    category: 'cost-markup',
    categoryLabel: 'Pricing & Margin',
    type: 'line',
    unit: 'bps',
    unitLabel: 'bps',
    description: 'Breaks total cost into fee and FX markup components',
    insightTemplate: 'Markup accounts for {percent}% of total cost',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount'],
    tooltipCopy: 'Fee bps = fee / amount. Markup bps = FX spread vs mid-market.',
    sourceNotes: 'Computed from provider quotes and mid-market benchmark',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'spread-distribution',
    title: 'Spread Distribution (p25/p50/p75)',
    category: 'cost-markup',
    categoryLabel: 'Pricing & Margin',
    type: 'line',
    unit: 'bps',
    unitLabel: 'bps',
    description: 'Dispersion of FX markup across providers',
    insightTemplate: 'Median spread is {value} bps',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount'],
    tooltipCopy: 'Shows p25, p50, and p75 markup levels across providers.',
    sourceNotes: 'Distribution computed from provider quotes captured each hour',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'provider-winner',
    title: 'Provider Winner Timeline',
    category: 'delivered-amount',
    categoryLabel: 'Competitive Dynamics',
    type: 'stacked',
    unit: 'provider',
    unitLabel: '',
    description: 'Which provider offered the best rate each day',
    insightTemplate: '{provider} has been #1 for {days} of the last 30 days',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount', 'payoutMethod'],
    tooltipCopy: 'Shows which provider delivered the most value on each day.',
    sourceNotes: 'Based on winner by delivered amount at each snapshot',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'leader-change-frequency',
    title: 'Leader Change Frequency',
    category: 'delivered-amount',
    categoryLabel: 'Competitive Dynamics',
    type: 'line',
    unit: 'count',
    unitLabel: '',
    description: 'Count of winner flips per day',
    insightTemplate: '{count} leader flips in the last 30 days',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount'],
    tooltipCopy: 'Tracks how often the leader changes across snapshots.',
    sourceNotes: 'Leader flips computed from snapshot winner data',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'leader-edge',
    title: 'Leader Edge vs #2',
    category: 'delivered-amount',
    categoryLabel: 'Competitive Dynamics',
    type: 'line',
    unit: 'bps',
    unitLabel: 'bps',
    description: 'Pricing edge of the leader over the runner-up',
    insightTemplate: 'Leader edge is {value} bps vs #2',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount'],
    tooltipCopy: 'Measures how far the leader is ahead of the runner-up in bps.',
    sourceNotes: 'Computed from winner and runner-up markup',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'pass-through-latency',
    title: 'Pass-Through Latency',
    category: 'delivered-amount',
    categoryLabel: 'Competitive Dynamics',
    type: 'line',
    unit: 'minutes',
    unitLabel: 'min',
    description: 'Lag between mid-market move and provider rate updates',
    insightTemplate: 'Median pass-through latency is {value} min',
    lastUpdated: '',
    requiredFilters: ['corridor'],
    tooltipCopy: 'Lower latency means faster price updates after FX moves.',
    sourceNotes: 'Derived from mid-market and provider rate timestamps',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'volatility-pulse',
    title: 'Volatility Pulse (RVI, bps)',
    category: 'volatility',
    categoryLabel: 'Volatility & Risk',
    type: 'bar',
    unit: 'bps',
    unitLabel: 'bps',
    description: 'Remittance Volatility Index in basis points (Gold indices).',
    insightTemplate: 'Volatility is {level} - monitor pricing windows',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount'],
    tooltipCopy: 'Higher RVI means more dispersion in provider pricing.',
    sourceNotes: 'Gold indices · $500 bank bucket · updated daily',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'quote-anomalies',
    title: 'Quote Stability',
    category: 'volatility',
    categoryLabel: 'Volatility & Risk',
    type: 'scatter',
    unit: 'deviation',
    unitLabel: 'sigma',
    description: 'Identifies providers with unusual pricing deviations',
    insightTemplate: '{count} anomalies detected in the last 7 days',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount'],
    tooltipCopy: 'Points far from the center indicate unusual pricing.',
    sourceNotes: 'Deviation from provider 30-day rolling average',
    defaultRange: '7d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'spread-volatility',
    title: 'Spread Volatility',
    category: 'volatility',
    categoryLabel: 'Volatility & Risk',
    type: 'line',
    unit: 'bps',
    unitLabel: 'bps',
    description: 'Volatility of the best-to-worst spread',
    insightTemplate: 'Spread volatility is {value} bps',
    lastUpdated: '',
    requiredFilters: ['corridor', 'amount'],
    tooltipCopy: 'Tracks how dispersed provider pricing becomes over time.',
    sourceNotes: 'Std dev of best-to-worst spread by snapshot',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'quote-success',
    title: 'Quote Success Rate',
    category: 'availability',
    categoryLabel: 'Operational Coverage',
    type: 'line',
    unit: 'percent',
    unitLabel: '%',
    description: 'Percentage of successful quote fetches by provider',
    insightTemplate: 'Overall reliability is {value}% ({direction} {delta}% vs 7d avg)',
    lastUpdated: '',
    requiredFilters: ['corridor'],
    tooltipCopy: 'Higher success rate means quotes are consistently available.',
    sourceNotes: 'Based on API response success rate',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'provider-availability',
    title: 'Provider Availability',
    category: 'availability',
    categoryLabel: 'Operational Coverage',
    type: 'line',
    unit: 'count',
    unitLabel: '',
    description: 'Providers returning quotes per interval',
    insightTemplate: 'Average availability is {value} providers',
    lastUpdated: '',
    requiredFilters: ['corridor'],
    tooltipCopy: 'Shows how many providers are active at each snapshot.',
    sourceNotes: 'Derived from successful quote fetches',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'data-freshness',
    title: 'Data Freshness (p50/p95)',
    category: 'availability',
    categoryLabel: 'Operational Coverage',
    type: 'line',
    unit: 'minutes',
    unitLabel: 'min',
    description: 'Quote age distribution in minutes',
    insightTemplate: 'p95 freshness is {value} min',
    lastUpdated: '',
    requiredFilters: ['corridor'],
    tooltipCopy: 'Lower values indicate fresher data.',
    sourceNotes: 'Calculated from quote capture timestamps',
    defaultRange: '7d',
    plusRanges: ['90d', '365d'],
  },
  {
    id: 'corridor-liquidity',
    title: 'Corridor Liquidity Signal',
    category: 'availability',
    categoryLabel: 'Operational Coverage',
    type: 'line',
    unit: 'index',
    unitLabel: 'index',
    description: 'Index based on quote density and provider coverage',
    insightTemplate: 'Liquidity index is {value}',
    lastUpdated: '',
    requiredFilters: ['corridor'],
    tooltipCopy: 'Higher scores indicate deeper quoting and coverage.',
    sourceNotes: 'Composite of quote density, coverage, and success rate',
    defaultRange: '30d',
    plusRanges: ['90d', '365d'],
  },
]

export function getChartById(chartId: string): ChartMetadata | undefined {
  return pulseChartRegistry.find(chart => chart.id === chartId)
}

export function getChartsByCategory(category: ChartCategory): ChartMetadata[] {
  return pulseChartRegistry.filter(chart => chart.category === category)
}

export function getAllCategories(): { category: ChartCategory, label: string, charts: ChartMetadata[] }[] {
  return Object.entries(CHART_CATEGORIES)
    .sort(([, a], [, b]) => a.order - b.order)
    .map(([category, { label }]) => ({
      category: category as ChartCategory,
      label,
      charts: getChartsByCategory(category as ChartCategory),
    }))
}

export function getRelatedCharts(chartId: string, limit = 3): ChartMetadata[] {
  const chart = getChartById(chartId)
  if (!chart) return []

  const sameCategory = pulseChartRegistry
    .filter(c => c.category === chart.category && c.id !== chartId)

  const otherCharts = pulseChartRegistry
    .filter(c => c.category !== chart.category && c.id !== chartId)

  return [...sameCategory, ...otherCharts].slice(0, limit)
}

export function isRangeGated(chartId: string, range: string, isPlus: boolean): boolean {
  if (isPlus) return false
  const chart = getChartById(chartId)
  if (!chart) return false
  return chart.plusRanges.includes(range as '90d' | '365d')
}
