name: ci/main

on:
  push:
    branches:
      - main
      - develop
      - staging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  core:
    name: ci/main
    uses: ./.github/workflows/ci.yml
    with:
      mode: main
