name: ci/pr

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  core:
    name: ci/pr
    uses: ./.github/workflows/ci-new.yml
    with:
      mode: pr
