name: ci/nightly

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  core:
    name: ci/nightly
    uses: ./.github/workflows/ci.yml
    with:
      mode: nightly
